name: Bootstrap, build and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - run: npm install npm@latest -g
    - run: npm -v
    - run: lerna bootstrap
    - run: lerna run lint
    
    - name: Archive results of build
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'push' }}
      with:
        name: vistorian
        path: packages/vistorian-web-sveltekit/build
